[phases.setup]
nixPkgs = ["python3", "ffmpeg", "opencv"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "python backend/app.py"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"